app:
  public-urls: /user/login,/user/register,/user/image/**, /user/*/image/**
jwt.secret: "secretblaabdd"
server:
  error:
    path: /erro
#    whitelabel:
#      enabled: false

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: rootpassword
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false